apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-home-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-home
  template:
    metadata:
      labels:
        app: smart-home
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: smart-home-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-home
  template:
    metadata:
      labels:
        app: smart-home
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: smart-home-service
spec:
  selector:
    app: smart-home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-home-ingress
spec:
  rules:
  - host: "smart-home.local"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smart-home-1-service
            port:
              number: 80
