apiVersion: v1
kind: Service
metadata:
  name: smart-home-nodeport-service
  namespace: smart-home-app
spec:
  selector:
    app: smart-home-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30002
  type: NodePort