apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-home-backend-hpa
  namespace: smart-home-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-home-backend-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # If CPU utilization > 50% then increase pod count to 2